/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

/**
 *
 * @author Asus
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAPORAN = new javax.swing.JLabel();
        TRANSAKSI = new javax.swing.JLabel();
        MASTER = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAPORAN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LAPORAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAPORANMouseClicked(evt);
            }
        });
        getContentPane().add(LAPORAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 100, 130));

        TRANSAKSI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TRANSAKSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TRANSAKSIMouseClicked(evt);
            }
        });
        getContentPane().add(TRANSAKSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 100, 130));

        MASTER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MASTER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MASTERMouseClicked(evt);
            }
        });
        getContentPane().add(MASTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiRumah/Dashboard Admin.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MASTERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MASTERMouseClicked
        // TODO add your handling code here:
        Master MASTERPAGE = new Master();
        MASTERPAGE.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_MASTERMouseClicked

    private void TRANSAKSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TRANSAKSIMouseClicked
        // TODO add your handling code here:
        Transaksi TRANSAKSIPAGE = new Transaksi();
        TRANSAKSIPAGE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TRANSAKSIMouseClicked

    private void LAPORANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAPORANMouseClicked
        // TODO add your handling code here:
        Laporan LAPORANPAGE = new Laporan();
        LAPORANPAGE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LAPORANMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAPORAN;
    private javax.swing.JLabel MASTER;
    private javax.swing.JLabel TRANSAKSI;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
