/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author Asus
 */
public class GajiKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form GajiKaryawan
     */
    public GajiKaryawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        karyawanIdField = new javax.swing.JTextField();
        jabatanIdField = new javax.swing.JTextField();
        simpan = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        karyawanNamaLabel = new javax.swing.JLabel();
        buttonsearch = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        gajiPokokJabatan = new javax.swing.JLabel();
        buttonsearch1 = new javax.swing.JLabel();
        gajiPokokLabel = new javax.swing.JLabel();
        bonusLabel = new javax.swing.JLabel();
        rumahTerjualLabel = new javax.swing.JLabel();
        totalGajiLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        karyawanIdField.setBorder(null);
        karyawanIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(karyawanIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 153, 140, -1));

        jabatanIdField.setBorder(null);
        jabatanIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(jabatanIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 153, 150, -1));

        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 240, 20));

        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 40, 30, 30));

        idLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idLabelMouseClicked(evt);
            }
        });
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 130, 30));

        karyawanNamaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanNamaLabelMouseClicked(evt);
            }
        });
        getContentPane().add(karyawanNamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, 30));

        buttonsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsearchMouseClicked(evt);
            }
        });
        getContentPane().add(buttonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 40, 30));

        jabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jabatanMouseClicked(evt);
            }
        });
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, 20));

        gajiPokokJabatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gajiPokokJabatanMouseClicked(evt);
            }
        });
        getContentPane().add(gajiPokokJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 130, 30));

        buttonsearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsearch1MouseClicked(evt);
            }
        });
        getContentPane().add(buttonsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 40, 20));
        getContentPane().add(gajiPokokLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 120, 30));
        getContentPane().add(bonusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 120, 30));
        getContentPane().add(rumahTerjualLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 120, 20));
        getContentPane().add(totalGajiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 200, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Gaji Karyawan.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void karyawanIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanIdFieldActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Transaksi TRANSAKSIPAGE = new Transaksi();
        TRANSAKSIPAGE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void buttonsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseClicked
        String idKaryawan = karyawanIdField.getText();
        if (idKaryawan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID Karyawan terlebih dahulu.");
            return;
        }

        try (Connection connection = koneksi.getConnection()) {
            String query = "SELECT * FROM karyawan WHERE `Id Karyawan` = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, idKaryawan);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                // Tampilkan nama karyawan
                idLabel.setText(resultSet.getString("Id Karyawan"));
                karyawanNamaLabel.setText(resultSet.getString("Nama Karyawan"));
            } else {
                JOptionPane.showMessageDialog(this, "Data karyawan tidak ditemukan.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data karyawan: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonsearchMouseClicked

    private void buttonsearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearch1MouseClicked
        String idJabatan = jabatanIdField.getText();
    String idKaryawan = karyawanIdField.getText();
    
    if (idJabatan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan ID Jabatan terlebih dahulu.");
        return;
    }
    
    if (idKaryawan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan ID Karyawan terlebih dahulu.");
        return;
    }

    try (Connection connection = koneksi.getConnection()) {
        // Query untuk mendapatkan data jabatan
        String jabatanQuery = "SELECT * FROM jabatan WHERE `Id Jabatan` = ?";
        PreparedStatement jabatanStatement = connection.prepareStatement(jabatanQuery);
        jabatanStatement.setString(1, idJabatan);
        ResultSet jabatanResult = jabatanStatement.executeQuery();

        if (jabatanResult.next()) {
            // Tampilkan jabatan dan gaji pokok
            jabatan.setText(jabatanResult.getString("Jabatan"));
            double gajiPokok = jabatanResult.getDouble("Gaji Pokok");
            
            // Format gaji pokok ke Rupiah
            gajiPokokLabel.setText(formatToRupiah(gajiPokok));
            gajiPokokJabatan.setText(formatToRupiah(gajiPokok));

            // Query untuk menghitung total bonus dan rumah terjual dari transaksi
            String transaksiQuery = "SELECT COUNT(*) as rumah_terjual, SUM(total_bonus) as total_bonus " +
                                  "FROM transaksi " +
                                  "WHERE karyawan_id = ? AND MONTH(timestamp) = MONTH(CURRENT_DATE()) " +
                                  "AND YEAR(timestamp) = YEAR(CURRENT_DATE())";
            PreparedStatement transaksiStatement = connection.prepareStatement(transaksiQuery);
            transaksiStatement.setString(1, idKaryawan);
            ResultSet transaksiResult = transaksiStatement.executeQuery();

            double totalBonus = 0;
            int rumahTerjual = 0;

            if (transaksiResult.next()) {
                rumahTerjual = transaksiResult.getInt("rumah_terjual");
                totalBonus = transaksiResult.getDouble("total_bonus");
            }

            // Tampilkan bonus dan rumah terjual dengan format
            bonusLabel.setText(formatToRupiah(totalBonus));
            rumahTerjualLabel.setText(String.valueOf(rumahTerjual));

            // Hitung total gaji dan format ke Rupiah
            double totalGaji = gajiPokok + totalBonus;
            totalGajiLabel.setText(formatToRupiah(totalGaji));
        } else {
            JOptionPane.showMessageDialog(this, "Data jabatan tidak ditemukan.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data: " + e.getMessage());
    }
    }//GEN-LAST:event_buttonsearch1MouseClicked

    private String formatToRupiah(double nominal) {
    java.text.NumberFormat formatRupiah = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
    String formatted = formatRupiah.format(nominal);
    // Hilangkan ,00 di belakang
    return formatted.replaceAll(",00", "");
    }
    private void karyawanNamaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanNamaLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_karyawanNamaLabelMouseClicked

    private void idLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idLabelMouseClicked

    private void gajiPokokJabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gajiPokokJabatanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gajiPokokJabatanMouseClicked

    private void jabatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jabatanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanMouseClicked

    private void jabatanIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jabatanIdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bonusLabel;
    private javax.swing.JLabel buttonsearch;
    private javax.swing.JLabel buttonsearch1;
    private javax.swing.JLabel gajiPokokJabatan;
    private javax.swing.JLabel gajiPokokLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jabatan;
    private javax.swing.JTextField jabatanIdField;
    private javax.swing.JTextField karyawanIdField;
    private javax.swing.JLabel karyawanNamaLabel;
    private javax.swing.JLabel rumahTerjualLabel;
    private javax.swing.JLabel simpan;
    private javax.swing.JLabel totalGajiLabel;
    // End of variables declaration//GEN-END:variables
}
