/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Popupdatajabatan extends javax.swing.JFrame {
    private Connection conn = new koneksi().getConnection(); 
    private DefaultTableModel tbl; 
//    public PenjualanRumah karyawan = null;
    private KaryawanSelectionListener selectionListener;

   
    public interface KaryawanSelectionListener {
        void onKaryawanSelected(String id, String jabatan, int gajiPokok);
    }
    /**
     * Creates new form Popupdatajabatan
     */
    public Popupdatajabatan(KaryawanSelectionListener listener) {
        this.selectionListener = listener;
        initComponents();
        datatable();
    }
    
    
    
    protected void datatable(){
    Object[] Baris = {"Id Jabatan", "Jabatan", "Gaji Pokok"};
        tbl = new DefaultTableModel(null, Baris);
        
        
        try {
            Statement st = (Statement)  koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM jabatan");
            
            while (rs.next()){
             tbl.addRow(new Object[]{
                rs.getString("Id Jabatan"),
                rs.getString("Jabatan"),
                rs.getString("Gaji Pokok"),
         
            });
             tblKaryawan.setModel(tbl); 
        }
 //           JOptionPane.showMessageDialog(null, "Koneksi Database  Berhasil");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        search = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 780, 190));

        txtcari.setBorder(null);
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 132, 140, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Jabatan", "Jabatan", "Gaji Pokok" }));
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 39, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Popup Data Jabatan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        int row = tblKaryawan.getSelectedRow();
        if (row >= 0) { // Pastikan ada row yang dipilih
            String id = tblKaryawan.getValueAt(row, 0).toString();
            String jabatan = tblKaryawan.getValueAt(row, 1).toString();
            int gajiPokok = Integer.parseInt(tblKaryawan.getValueAt(row, 2).toString());

            if (selectionListener != null) {
                selectionListener.onKaryawanSelected(id, jabatan, gajiPokok);
            }
            this.dispose();
        }
    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Jabatan");
        tbl.addColumn("Jabatan");
        tbl.addColumn("Gaji Pokok");

        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            String selectedColumn = (String) jComboBox1.getSelectedItem();
            String searchText = txtcari.getText();

            String query = "SELECT * FROM jabatan WHERE `" + selectedColumn + "` LIKE '%" + searchText + "%'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("Id Jabatan"),
                    rs.getString("Jabatan"),
                    rs.getString("Gaji Pokok"),
                });
                tblKaryawan.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
    }//GEN-LAST:event_searchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popupdatajabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popupdatajabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popupdatajabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popupdatajabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Berikan null sebagai listener atau buat dummy listener
            new Popupdatajabatan(new Popupdatajabatan.KaryawanSelectionListener() {
                @Override
                public void onKaryawanSelected(String id, String jabatan, int gajiPokok) {
                    System.out.println("Jabatan terpilih: " + jabatan);
                }
            }).setVisible(true);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel search;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
