/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Asus
 */
public class Popupdataclient extends javax.swing.JFrame {
    private Connection conn = new koneksi().getConnection(); 
//    private DefaultTableModel tabmode; 
    public PenjualanRumah client = null;
    private DefaultTableModel tbl;
    
    /**
     * Creates new form Popupdataclient
     */
    public Popupdataclient() {
        initComponents();
        datatable();
    }
    
    protected void datatable(){
    Object[] Baris = {
            "Id Client",
            "NIK",
            "Nama Client",
            "Nomor KK",
            "NPWP",
            "Asuransi",
            "Gaji",
            "Alamat"
        };
        tbl = new DefaultTableModel(null, Baris);
        
        try {
            Statement st = (Statement)  koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM client");
            
            while (rs.next()){
             tbl.addRow(new Object[]{
                rs.getString("Id Client"),
                rs.getString("NIK"),
                rs.getString("Nama Client"),
                rs.getString("Nomor KK"),
                rs.getString("NPWP"),
                rs.getString("Asuransi"),
                rs.getString("Gaji"),
                rs.getString("Alamat"),
         
            });
             tblclient.setModel(tbl); 
        }
 //           JOptionPane.showMessageDialog(null, "Koneksi Database  Berhasil");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 39, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Client", "NIK", "Nama Client", "Nomor KK", "NPWP", "Asuransi", "Gaji", "Alamat" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        txtcari.setBorder(null);
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, -1));

        tblclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblclientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblclient);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 780, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Popup Data Client.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 426));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclientMouseClicked
        // TODO add your handling code here:
        int tabelPelanggan = tblclient.getSelectedRow();
        client.nik = tblclient.getValueAt(tabelPelanggan, 1).toString();
        client.client = tblclient.getValueAt(tabelPelanggan, 2).toString();
        client.kk = tblclient.getValueAt(tabelPelanggan, 3).toString();
        client.npwp = tblclient.getValueAt(tabelPelanggan, 4).toString();
        client.asuransi = tblclient.getValueAt(tabelPelanggan, 5).toString();
        client.gaji = tblclient.getValueAt(tabelPelanggan, 6).toString();
        client.alamat = tblclient.getValueAt(tabelPelanggan, 7).toString();
        client.itemTerpilihclient();
        this.dispose();
    }//GEN-LAST:event_tblclientMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Client");
        tbl.addColumn("NIK");
        tbl.addColumn("Nama Client");
        tbl.addColumn("Nomor KK");
        tbl.addColumn("NPWP");
        tbl.addColumn("Asuransi");
        tbl.addColumn("Gaji");
        tbl.addColumn("Alamat");

        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            String selectedColumn = (String) jComboBox1.getSelectedItem();
            String searchText = txtcari.getText();

            String query = "SELECT * FROM client WHERE `" + selectedColumn + "` LIKE '%" + searchText + "%'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("Id Client"),
                    rs.getString("NIK"),
                    rs.getString("Nama Client"),
                    rs.getString("Nomor KK"),
                    rs.getString("NPWP"),
                    rs.getString("Asuransi"),
                    rs.getString("Gaji"),
                    rs.getString("Alamat"),
                });
                tblclient.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
    }//GEN-LAST:event_searchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popupdataclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popupdataclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popupdataclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popupdataclient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popupdataclient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel search;
    private javax.swing.JTable tblclient;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
