/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Asus
 */
public class Popupdatarumah extends javax.swing.JFrame {
    private Connection conn = new koneksi().getConnection(); 
    private DefaultTableModel tabmode; 
    public PenjualanRumah rumah = null;
    
    /**
     * Creates new form Popupdataclient
     */
    public Popupdatarumah() {
        initComponents();
        datatable();
    }
    
    protected void datatable(){
    Object[] Baris = {"Tipe Rumah","Luas Bangunan","Luas Tanah","Kamar Tidur","Kamar Mandi", "Lantai", "Listrik", "Sumber Air", "Deskripsi","Harga Rumah"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem = txtcari.getText();

    try {
        String sql = "SELECT * FROM tipe_rumah where `Id Rumah` like '%" + cariitem + "%' or `Tipe` like '%" + cariitem + "%' order by `Id Rumah` asc";
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            tabmode.addRow(new Object[]{
                hasil.getString(2),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(8),
                hasil.getString(9),
                hasil.getString(10),
                hasil.getString(11),
                hasil.getString(7),
                hasil.getString(12)
            });
        }
        tblrumah.setModel(tabmode);
    } catch (Exception e) {
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrumah = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcari.setBorder(null);
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, -1));

        tblrumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblrumah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrumahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblrumah);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 780, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiRumah/Popup Data Client.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 426));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblrumahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrumahMouseClicked
        // TODO add your handling code here:
        int tabelRumah = tblrumah.getSelectedRow();
        rumah.tipe = tblrumah.getValueAt(tabelRumah, 0).toString();
        rumah.lb = tblrumah.getValueAt(tabelRumah, 1).toString();
        rumah.lt = tblrumah.getValueAt(tabelRumah, 2).toString();
        rumah.kt = tblrumah.getValueAt(tabelRumah, 3).toString();
        rumah.km = tblrumah.getValueAt(tabelRumah, 4).toString();
        rumah.lantai = tblrumah.getValueAt(tabelRumah, 5).toString();
        rumah.listrik = tblrumah.getValueAt(tabelRumah, 6).toString();
        rumah.air = tblrumah.getValueAt(tabelRumah, 7).toString();
        rumah.desk = tblrumah.getValueAt(tabelRumah, 8).toString();
        rumah.harga = tblrumah.getValueAt(tabelRumah, 9).toString();
        rumah.itemTerpilihrumah();
        this.dispose();
    }//GEN-LAST:event_tblrumahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popupdatarumah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblrumah;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
