/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Asus
 */
public class Popupdatarumah extends javax.swing.JFrame {
    private Connection conn = new koneksi().getConnection(); 
    private DefaultTableModel tbl; 
    public PenjualanRumah rumah = null;
    
    /**
     * Creates new form Popupdataclient
     */
    public Popupdatarumah() {
        initComponents();
        datatable();
    }
    
    NumberFormat numberFormat = NumberFormat.getNumberInstance();
    
    protected void datatable(){
    Object[] Baris = {
            "Tipe",
            "Luas Bangunan",
            "Luas Tanah",
            "Kamar Tidur",
            "Kamar Mandi",
            "Lantai",
            "Listrik",
            "Sumber Air",
            "Alamat",
            "Harga Rumah"
        };

        tbl = new DefaultTableModel(null, Baris);
        
        try {
        Statement st = koneksi.getConnection().createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM tipe_rumah");
        
        while (rs.next()) {
            tbl.addRow(new Object[]{
                rs.getString("Tipe"), // Format tanpa simbol mata uang
                numberFormat.format(rs.getDouble("Luas Bangunan")),
                numberFormat.format(rs.getDouble("Luas Tanah")),
                rs.getString("Kamar Tidur"),
                rs.getString("Kamar Mandi"),
                rs.getString("Lantai"),
                rs.getString("Listrik"),
                rs.getString("Sumber Air"),
                rs.getString("Deskripsi"), // Format tanpa simbol mata uang
                numberFormat.format(rs.getDouble("Harga Rumah")) // Format tanpa simbol mata uang
            });
        }
        tblrumah.setModel(tbl);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        search = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblrumah = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Rumah", "Tipe", "Harga Pokok", "Luas Bangunan", "Luas Tanah", "Kamar Tidur", "Kamar Mandi", "Lantai", "Listrik", "Sumber Air", "Harga Rumah", "Deskripsi", "Total Bonus" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 39, 25));

        txtcari.setBorder(null);
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 132, 140, -1));

        tblrumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblrumah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrumahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblrumah);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 780, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Popup Data Rumah.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 426));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblrumahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrumahMouseClicked
        // TODO add your handling code here:
        int tabelRumah = tblrumah.getSelectedRow();
        rumah.tipe = tblrumah.getValueAt(tabelRumah, 0).toString();
        rumah.lb = tblrumah.getValueAt(tabelRumah, 1).toString();
        rumah.lt = tblrumah.getValueAt(tabelRumah, 2).toString();
        rumah.kt = tblrumah.getValueAt(tabelRumah, 3).toString();
        rumah.km = tblrumah.getValueAt(tabelRumah, 4).toString();
        rumah.lantai = tblrumah.getValueAt(tabelRumah, 5).toString();
        rumah.listrik = tblrumah.getValueAt(tabelRumah, 6).toString();
        rumah.air = tblrumah.getValueAt(tabelRumah, 7).toString();
        rumah.desk = tblrumah.getValueAt(tabelRumah, 8).toString();
        rumah.harga = tblrumah.getValueAt(tabelRumah, 9).toString();
        rumah.itemTerpilihrumah();
        this.dispose();
    }//GEN-LAST:event_tblrumahMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id Client");
        tbl.addColumn("NIK");
        tbl.addColumn("Nama Client");
        tbl.addColumn("Nomor KK");
        tbl.addColumn("NPWP");
        tbl.addColumn("Asuransi");
        tbl.addColumn("Gaji");
        tbl.addColumn("Alamat");

        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            String selectedColumn = (String) jComboBox1.getSelectedItem();
            String searchText = txtcari.getText();

            String query = "SELECT * FROM tipe_rumah WHERE `" + selectedColumn + "` LIKE '%" + searchText + "%'";
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("Id Rumah"),
                    rs.getString("Tipe"),
                    numberFormat.format(rs.getDouble("Harga Pokok")), // Format tanpa simbol mata uang
                    numberFormat.format(rs.getDouble("Luas Bangunan")),
                    numberFormat.format(rs.getDouble("Luas Tanah")),
                    rs.getString("Kamar Tidur"),
                    rs.getString("Kamar Mandi"),
                    rs.getString("Lantai"),
                    rs.getString("Listrik"),
                    rs.getString("Sumber Air"),
                    numberFormat.format(rs.getDouble("Harga Rumah")), // Format tanpa simbol mata uang
                    rs.getString("Deskripsi"),
                    numberFormat.format(rs.getDouble("Total Bonus")) // Format tanpa simbol mata uang
                });
                tblrumah.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal" + e.getMessage());
        }
    }//GEN-LAST:event_searchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popupdatarumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popupdatarumah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel search;
    private javax.swing.JTable tblrumah;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
