/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiRumah;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class Report_RancanganAnggaranBiaya extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private Connection conn;
    /**
     * Creates new form Report_RancanganAnggaranBiaya
     */
    public Report_RancanganAnggaranBiaya() {
        initComponents();
        conn = new koneksi().getConnection();
        initTable();
        loadTipeComboBox();
        loadAllData();
    }
    
    private void initTable() {
        tableModel = new DefaultTableModel(
            new Object[]{"ID RAB", "Tipe", "Keterangan", "Harga"}, 
            0
        );
        table.setModel(tableModel);
        
        // Format kolom harga
        table.getColumnModel().getColumn(3).setCellRenderer(new NumberRenderer());
    }
    
     private void loadTipeComboBox() {
        try {
            String sql = "SELECT DISTINCT Tipe FROM RAB ORDER BY Tipe";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            Vector<String> tipeList = new Vector<>();
            tipeList.add("Semua Tipe"); // Opsi untuk menampilkan semua
            
            while (rs.next()) {
                tipeList.add(rs.getString("Tipe"));
            }
            
            comboBoxTipe.setModel(new DefaultComboBoxModel<>(tipeList));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error memuat daftar tipe: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
     
     private void loadAllData() {
        loadData(null);
        lblTotalHarga.setText("Rp -"); // Reset ke default saat menampilkan semua data
    }
    
    private void loadData(String filterTipe) {
        tableModel.setRowCount(0); // Clear existing data
        double totalHarga = 0; // Variabel untuk menyimpan total
        
        String sql = "SELECT `Id RAB`, Tipe, Keterangan, Harga FROM RAB ";
        
        if (filterTipe != null && !filterTipe.equals("Semua Tipe")) {
            sql += "WHERE Tipe = ? ";
        }
        
        sql += "ORDER BY Tipe, Keterangan";
        
        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            if (filterTipe != null && !filterTipe.equals("Semua Tipe")) {
                pst.setString(1, filterTipe);
            }
            
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                double harga = rs.getDouble("Harga");
                tableModel.addRow(new Object[]{
                    rs.getString("Id RAB"),
                    rs.getString("Tipe"),
                    rs.getString("Keterangan"),
                    harga
                });
                totalHarga += harga; // Akumulasi total harga
            }
            
            // Update label total harga
            updateTotalLabel(totalHarga);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Error memuat data RAB: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateTotalLabel(double total) {
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("id", "ID"));
        nf.setMaximumFractionDigits(0);
        lblTotalHarga.setText("Rp " + nf.format(total));
    }
    
    
    
    // NumberRenderer untuk format mata uang
    class NumberRenderer extends DefaultTableCellRenderer {
        private java.text.NumberFormat nf;
        
        public NumberRenderer() {
            super();
            nf = java.text.NumberFormat.getNumberInstance();
            nf.setMaximumFractionDigits(0);
            setHorizontalAlignment(RIGHT);
        }
        
        @Override
        public void setValue(Object value) {
            if (value instanceof Number) {
                value = nf.format(value);
            }
            super.setValue(value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnRefresh = new javax.swing.JLabel();
        btnRefresh1 = new javax.swing.JLabel();
        btnShowAll = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        comboBoxTipe = new javax.swing.JComboBox<>();
        lblTotalHarga = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 780, 130));

        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 185, 180, 26));

        btnRefresh1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefresh1MouseClicked(evt);
            }
        });
        getContentPane().add(btnRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 485, 180, 26));

        btnShowAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowAllMouseClicked(evt);
            }
        });
        getContentPane().add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 250, 26, 26));

        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 30, 30));

        comboBoxTipe.setBackground(new java.awt.Color(229, 245, 255));
        comboBoxTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxTipe.setBorder(null);
        getContentPane().add(comboBoxTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 140, -1));
        getContentPane().add(lblTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 428, 140, 20));

        jLabel2.setText("Total :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rancangan Anggaran Biaya.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        // Get selected row
    }//GEN-LAST:event_tableMouseClicked

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        String selectedTipe = (String) comboBoxTipe.getSelectedItem();
        loadData(selectedTipe); // Akan otomatis update total harga
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void btnRefresh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefresh1MouseClicked
        // TODO add your handling code here:
        String selectedTipe = (String) comboBoxTipe.getSelectedItem();
        new ReportRancanganAnggaranBiaya().printRABByTipe(selectedTipe);
    }//GEN-LAST:event_btnRefresh1MouseClicked

    private void btnShowAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowAllMouseClicked
        // TODO add your handling code here:
        loadAllData();
            comboBoxTipe.setSelectedIndex(0); // Reset ke "Semua Tipe"
    }//GEN-LAST:event_btnShowAllMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Laporan LAPORANPAGE = new Laporan();
        LAPORANPAGE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_RancanganAnggaranBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_RancanganAnggaranBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_RancanganAnggaranBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_RancanganAnggaranBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_RancanganAnggaranBiaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JLabel btnRefresh1;
    private javax.swing.JLabel btnShowAll;
    private javax.swing.JComboBox<String> comboBoxTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
